spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mail_DB?serverTimezone=Asia/Seoul
    username: root
    password: KimHanJu080210@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: hanju12345678900@gmail.com
    password: fvon qjuv ivuq pnmx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    auth-code-expiration-millis: 1800000


  data:
    redis:
      port: 6379
      host: localhost