spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: hanju12345678900@gmail.com
    password: fvon qjuv ivuq pnmx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimout: 5000
    auth-code-expiration-millis: 1800000
